<?php

namespace EDouna\LaravelDBBackup\Test;

use EDouna\LaravelDBBackup\LaravelDBBackupProvider;

class TestCase extends \Orchestra\Testbench\TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function getPackageProviders($app)
    {
        return [
            LaravelDBBackupProvider::class
        ];
    }

    public function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub
    }

    protected function useMySqlConnection($app)
    {
        $app->config->set('database.default', 'mysql');
    }

    protected function useSqliteConnection($app)
    {
        $app->config->set('database.default', 'sqlite');
    }

    protected function useStoragePath($app)
    {
        $app->config->set('db-backup.backup_folder', storage_path('db-backups'));
    }
}
